console commands for list management
ihabunek/toot pull request #341
Opened 2023-03-15 03:40 UTC by danschwarz

List view, create, delete, view accounts for one list, add account to list, remove account from list.

Most work but add/remove account have problems os this is in draft for now.

2023-03-20 00:31 UTC, danschwarz commented
Added `toot list_add_account` and `toot list_remove_account` commands.  This makes the list-handling command set feature-complete.

2023-03-26 09:02 UTC, ihabunek requested changes
Hey thanks for this. Mostly looks good, I have some suggestions for change, mostly to make it less verbose.

2023-03-26 22:43 UTC, danschwarz commented on toot/tui/scroll.py
>  #
Yes I always do a `git diff` sanity check; this must have gotten through when I wasn't paying close enough attention. I haven't tried `commit -p`; I'll do that.

2023-03-26 22:53 UTC, danschwarz commented on toot/console.py
> +            }),
fixed

2023-03-26 22:59 UTC, danschwarz commented on toot/console.py
> +            }),
fixed

2023-03-26 23:09 UTC, danschwarz commented on toot/console.py
> +            }),
This works. I'll implement.

2023-03-26 23:09 UTC, danschwarz commented on toot/console.py
> +        name="list_add_account",
Fixed

2023-03-26 23:10 UTC, danschwarz commented on toot/console.py
> +        name="list_remove_account",
Fixed

2023-03-27 01:26 UTC, danschwarz commented on toot/commands.py
> +    except Exception as ex:
removed

2023-03-30 10:11 UTC, ihabunek commented
Thanks! I merged this manually and added some tests.

I changed the "toot lists" command to display as a table, which seemed nicer.

2023-03-30 10:11 UTC, closed without merging